### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by nbish11**
This PR only serves to pave the way to a full refactor using Generators. As it stands, the `ChangelogGenerator` class is just to messy to fully implement Generators in it (hence the use of the `iterator_to_array()` method).

There is still, however marginal, performance improvements in this PR (mainly in memory use). Also, less timeouts for repos with lots of releases.

### CODE REVIEW

**Comment by nbish11** [comment]
@ins0 Any feedback?

**Comment by ins0** [comment]
@nbish11 i'm very sorry but i totally forget this pr - i will check it out tonight - promise!

**Comment by nbish11** [comment]
I've still got to refactor the `iterator_to_array()` functions out of the `ChangelogGenerator` class before this PR is ready.

**Comment by nbish11** [comment]
@ins0 You can go ahead and take a look at this PR now and let me know what you think.

Before refactoring the `iterator_to_array()` functions out of the `ChangelogGenerator` class, I plan on submitting another PR which will integrate performance testing. That way, when the `iterator_to_array()` functions get factored out, everyone will be able to see the results for themselves.

**Pull request merged**
