### PR TITLE
Feature allow custom headers

### PR DESCRIPTION
**Pull request by murrant**
Also allows custom types by defining them in both $issueMappings and $typeHeadings

I added my copyright in places I thought appropriate, let me know if I messed up.
Would you like to bump the release for this here or do that seperately?

### CODE REVIEW

**Comment by murrant** [comment]
@ins0 still around?

**Comment by ins0** [comment]
@murrant yes i'm here. sry for my late response. i will check this pr this week for sure!

> Would you like to bump the release for this here or do that seperately?

no, i think i will remove the version annotations in each file as they will not provide any useful information. what is your thought about this?

**Comment by murrant** [comment]
Not much gain for marking versions inside files.

**Comment by nbish11** [comment]
👍 Love this @murrant!

**Comment by nbish11** [comment]
@ins0 Are you planning on merging this?

**Comment by ins0** [comment]
merged, thanks @murrant for your help. sry for the long response time, was in hospital.

**Comment by murrant** [comment]
No worries, I just used my own branch in the meantime.  Hope you are doing better now.

**Pull request merged**
